### ISSUE TITLE
url /pub/job backwards compatibiltiy

### ISSUE THREAD

**Issue by jsandroos** [TheRacetrack/plugin-python-job-type#13]
Hi @LookACastle 

Regarding the fatman -> job degreasing, we had discussed backwards compatibility. This has been interpreted in the widest possible terms in the Lab and hence people have scripts calling the api endpoints, e.g. /pub/fatman/<name>/<version>/health, like so:

`curl -X 'GET' \
  '<dev url>/pub/job/<name>/<version>/health' \
  -H 'accept: application/json'`
  
which now fail with:
`{"detail":"Not Found"}`

I suspect this is due to the api endpoint no longer being hosted at /pub/fatman but only at /pub/job.

Should we add backwards compatibility here?

**Comment by iszulcdeepsense** [comment]
Fortunately, `mount_at_base_path` can accept multiple base path patterns as an argument: 
https://github.com/TheRacetrack/plugin-python-job-type/blob/04bf59634ee23645d46eb16099304c7593905f67/python3-job-type/python_wrapper/racetrack_commons/api/asgi/proxy.py#L6

So changing this line
https://github.com/TheRacetrack/plugin-python-job-type/blob/04bf59634ee23645d46eb16099304c7593905f67/python3-job-type/python_wrapper/job_wrapper/api.py#L97 should do the trick.

**Comment by JosefAssadERST** [comment]
Is there a test we could have somewhere that would have caught this detail?

**Comment by LookACastle** [comment]
It's possible. There's a decent chance such a test would've had the endpoint it was contacting renamed as well though.

**Comment by iszulcdeepsense** [comment]
Turns out the unit test wasn't checking against any base path. Now it's covered https://github.com/TheRacetrack/plugin-python-job-type/pull/14/commits/924638233aab47ab0f6c2fce10f66573a5825336
