### ISSUE TITLE
Rename job_wrapper module

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/plugin-python-job-type#24]
Some people say this import line is confusing `from job_wrapper.call import call_job`:
- https://github.com/TheRacetrack/plugin-python-job-type/blob/master/sample/python-chain/entrypoint.py#L3
- https://github.com/TheRacetrack/racetrack/blob/master/sample/python-chain/entrypoint.py#L3

`job_wrapper` is a mysterious package. It looks like it's a third-party lib installed from PyPI, while in fact, it's an internal package used by a job type plugin. Maybe it should be called `racetrack_job_wrapper` to fit in the other imports scheme `from racetrack_commons import ...`, `from racetrack_client import ...` to indicate a relationship with the racetrack ecosystem.

**Comment by Koshmaar** [comment]
+1 for `racetrack_job_wrapper`
